### ISSUE TITLE
Pandora login for apps on iso-search

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/TraceR#32]
> @f-lukas @jan-abel-inwt here an update regarding the login:
> 
> Two servers are used for our apps, iso-app and iso-search.
> - **iso-app** will remain as it is and all modelling apps will run here **without** any login
> - **iso-search** will get the Pandora-Login:
>   - the Data search apps ([main](https://pandorasearch.earth/), [beta](https://isomemoapp.com/app/iso-memo-data-app-beta)) will now require a login
>   - we shift TraceR, MapR and all other apps that need the login to _iso-search_ 

 _Originally posted by @arunge in [#5](https://github.com/Pandora-IsoMemo/TraceR/issues/5#issuecomment-2604618168)_

@jan-abel-inwt Could you please setup the login for iso-search and shift TraceR, MapR and InquiryR to iso-search? Please start with TraceR first and let use test the login before we move other apps.

**Comment by arunge** [comment]
_From https://github.com/Pandora-IsoMemo/TraceR/issues/5#issuecomment-2636249392_


@jan-abel-inwt Regarding Pandora login:
- when I [tried to setup](https://github.com/Pandora-IsoMemo/drat/issues/41#issuecomment-2354799558) _Orcid_ login for flarum, I found a description for a [config](https://orcid.org/.well-known/openid-configuration).
- however, we need Pandora login (not Orcid) here:
  - [Pandora](https://pandoradata.earth/) is based on [CKAN](https://ckan.org/) which uses SAML2 (https://ckan.org/blog/using-saml2-authentication-ckan, https://docs.ckan.org/en/2.9/api/#authentication-and-api-tokens)
  - for shinyproxy we have here a [config help](https://www.shinyproxy.io/documentation/configuration/#saml-20) and [faqs](https://www.shinyproxy.io/faq/)

Can you setup the authentication? Let me know if you have questions!

**Comment by jan-abel-inwt** [comment]
My initial assessment, based on what you've found, is that the SAML2 plugin is very likely not installed on the Pandora data Website (CKAN server). This means we have two main paths:

1. Get the SAML2 plugin installed by the Pandora/CKAN admins. 
2. Explore an alternative authentication method if plugin installation isn't feasible. (e.g. openid via orcid id)

**Comment by jan-abel-inwt** [comment]
## Authentication with OpenID via ORCID


### ORCID Application Setup

1. Create an account at [orcid.org](https://orcid.org/)
2. Register for ORCID PUBLIC API credentials via [Developer tools](https://orcid.org/developer-tools) to obtain Client ID and Client Secret.

**CRITICAL STEP: Register the Redirect URI**

Register the ShinyProxy callback URL in the ORCID application settings. We need to use https and ensure the URL path is an exact match for the domain (e.g., pandorasearch.earth):

<img width="1010" height="1258" alt="Image" src="https://github.com/user-attachments/assets/9521f06d-e2a6-487b-8f7c-50e91bee396e" />

### ShinyProxy Configuration

- To the Shinyproxy `application.yaml` config i added the following:

  ```yaml
  proxy:
    title: Pandora & IsoMemo applications
    authentication: openid
    openid:
      # ORCID Endpoints
      auth-url: https://orcid.org/oauth/authorize
      token-url: https://orcid.org/oauth/token
      jwks-url: https://orcid.org/oauth/jwks
      userinfo-url: https://orcid.org/oauth/userinfo
      # Credentials
      client-id: <CLIENT_ID>
      client-secret: <CLIENT_SECRET>
      # set orcID as shinyproxy username
      username-attribute: sub
  ...
  server:
    forward-headers-strategy: native
   ```

  Additional information as envs are possible via SpEL. For the username, it would look like this:

  ```yaml
  ...
  specs:
  - id: <APP>
    display-name: <DISPLAY_NAME>
    container-image: <IMAGE_NAME>
    container-env:
      APP_USER_NAME: '#{oidcUser.getClaimAsString("given_name") + " " + oidcUser.getClaimAsString("family_name")}'
   ...
   ```

### Nginx Configuration

When ShinyProxy runs behind a reverse proxy (like Nginx) that handles SSL/TLS (https), the proxy must correctly forward the protocol scheme. The header used to pass the original protocol ($scheme) to the backend application was incorrect/outdated. I had to adjust the nginx files `pandora.conf` & `isomemo.conf`:

  ```
  #old:
  #proxy_set_header        X-Forwarded-Protocol    $scheme;
  
  #new:
  proxy_set_header        X-Forwarded-Proto    $scheme;
  ```

### User Login

If a user tries to log in, for example to or example https://pandorasearch.earth/, they will be redirected to ORCID:

1. **ORCID Sign In:** User signs in with their ORCID credentials.

<img width="660" height="808" alt="Image" src="https://github.com/user-attachments/assets/2f0121a2-2fa3-489d-9f69-043648e80a80" />

2. **Authorization:** User sees the application name (Pandora & IsoMemo Computational Lab) and is asked to Authorize access to their ORCID iD and public record information.

<img width="684" height="939" alt="Image" src="https://github.com/user-attachments/assets/1b6b9fe5-164c-449f-8e22-30591aba63e0" />

3. **Redirect:** After authorizing, the user is redirected back to the ShinyProxy application and logged in.
